# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# It uses the latest stable version of Node.js.
# This pipeline is triggered on a push to any branch. 
name: CI

on:
  push:
    branches: 
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_Code
        uses: actions/checkout@v4

      - name: Setup_Node
        uses: actions/setup-node@v4
        with:
          node-version: 'node'

      - name: Install_Dependencies
        run: npm install --save-dev mocha chai supertest

      - name: Build 
        run: npm run build

      - name: Run_Tests
        run: npm test
