# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

#
# The "On" node defines what events or conditions in the repository cause the workflow to be executed. 
# In this case, we are executing the workflow on any push to any branch, including developer branches, 
# as well as any pull request created to the main branch.  Note, this runs the CI pipeline when the 
# developer CREATES the PR to request merging their code to the main branch, and NOT on the actual 
# merge. This is to ensure the code builds and passes all tests at the time the PR is created.  When 
# the PR is merged, the deployment pipeline will be triggered.  If the PR is changed as part of the 
# reviews, any pushes will also trigger this CI pipeline again. 
#
on:
  push:
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
