# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# It uses the latest stable version of Node.js.
# This pipeline is triggered on a push to any branch. 
name: CI

on:
  push:        # On a push
    branches: 
      - '**'   # Any branch
      
jobs:

  # Build and test pipeline 
  build-and-test:
    runs-on: ubuntu-latest

    # Execution steps of the pipeline
    steps:

    # Check out the code from GitHub repository
    - name: Checkout_Code
      uses: actions/checkout@v4

    # Set up the Node.js environment 
    - name: Setup_Node
      uses: actions/setup-node@v4
      with:
        node-version: 'node'

    # Install all needed dependencies 
    - name: Install_Dependencies 
      run: npm run build

    # Run test cases 
    - name: Run_Tests
      run: npm test
